<a href="https://colab.research.google.com/github/FmRadioAlex/-----/blob/main/goit_data_hw_4_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import random

1-Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [ ]:
np.array([1,2,3,4,5,6,7,8,9,10])

2-Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [ ]:
np.zeros([3,3])

3-Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [ ]:
np.random.randint(1,10,size=(5,5))

4-Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення

In [ ]:
np.random.rand(4,4)

5-Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [ ]:
A=np.random.randint(0,11,size=(5))
B=np.random.randint(0,11,size=(5))
print(A,B)
print(A+B)
print(A-B)
print(A*B)

6-Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [ ]:
A=np.random.randint(0,10,size=(7))
B=np.random.randint(0,10,size=(7))
print(f'Матриця А {A}\nМатриця В {B}')
print(f'Добуток {np.dot(A,B)}')

7-Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою

In [ ]:
A=np.random.randint(0,10,size=(2,2))
B=np.random.randint(0,10,size=(2,3))
print(f'Матриця А\n{A}\nМатриця В\n{B}')
np.dot(A,B)

8-Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [ ]:
B=np.random.randint(0,10,size=(3,3))
print(B)
print(np.linalg.inv(B))

[[8 2 0]
 [1 1 0]
 [0 3 9]]
[[ 0.16666667 -0.33333333  0.        ]
 [-0.16666667  1.33333333  0.        ]
 [ 0.05555556 -0.44444444  0.11111111]]


9-Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [ ]:
A=np.random.randint(0,2,size=(4,4))
print(A,'\n\n')
print(A.T)

10-Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [ ]:
A=np.random.randint(0,10,size=(3,4))
B=np.random.randint(0,10,size=4)
print(A,'\n\n',B,end="\n\n")
print(A*B,"\n\n")
print(np.dot(A,B))

11-Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [ ]:
A=np.random.rand(2,3)
B=np.random.rand(3)
print(A,'\n\n',B,end="\n\n")
print(A*B,"\n\n")
print(np.dot(A,B))

12-Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [ ]:
A=np.random.randint(0,10,size=(2,2))
B=np.random.randint(0,10,size=(2,2))
print(A,end='\n\n')
print(B,end='\n\n')
A*B

13-Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток

In [ ]:
A=np.random.randint(0,10,size=(2,2))
B=np.random.randint(0,10,size=(2,2))
np.dot(A,B)

14-Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [ ]:
A=np.random.randint(0,100,size=(5,5))
print(A)
print(f'Summa = {np.sum(A)}')

15-Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [ ]:
A=np.random.randint(0,10,size=(4,4))
B=np.random.randint(0,10,size=(4,4))
A-B

16-Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [ ]:
A=np.random.rand(3,3)
print(A)
np.sum(A,axis=1)

17-Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [ ]:
A=np.random.randint(0,10,size=(3,4))
print(A)
A**2

18-Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [ ]:
A=np.random.randint(0,50,size=(4))
print(A)
np.sqrt(A)

[38 45  7 45]


array([6.164414  , 6.70820393, 2.64575131, 6.70820393])