<a href="https://colab.research.google.com/github/FmRadioAlex/-----/blob/main/goit_data_hw_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Завдання
  # Дане домашнє завдання буде повністю пов'язане з лінійною регресією та її реалізацією. Отож розіб'ємо наше домашнє завдання на декілька частин:

In [ ]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from sklearn.linear_model import LinearRegression

import seaborn as sns

In [ ]:
from sklearn.preprocessing import normalize as norm
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler as min_max

напишіть функцію гіпотези лінійної регресії у векторному вигляді;

In [ ]:
table_model=pd.read_csv("Housing.csv")
table_model.head()
data=table_model

напишіть функцію гіпотези лінійної регресії у векторному вигляді;
$$h(x) = w_0 + w_1*x$$
$$h(x_1,x_2) = w_0 + w_1*x_1 + w_2*x_2 $$
$$h(x_1,...,x_n) = w_0 + w_1*x_1 + ... + w_n*x_n $$
$$ h(x_i) = w0 + \sum_{i=1}^n w_n*x_n $$

$$ \vec{x} = \begin{pmatrix} 1 \\ x_1 \\ ..  \\ x_n   \end{pmatrix},
\vec{w} = \begin{pmatrix} w_0 \\ w_1 \\ ..\\ w_n \end{pmatrix}$$

# математичні функціі /

$$ h(\vec{x})= \vec{x} \cdot \vec{w}  $$

In [ ]:
def hypothesis(X, theta): #X=масив з декільками данними  theta=
    return np.dot(X, theta)

In [ ]:
def feature_normalize(X):
    mu = np.mean(X, axis=0)
    sigma = np.std(X, axis=0)
    X_norm = (X - mu) / sigma
    return X_norm

створіть функцію для обчислення функції втрат у векторному вигляді

$$ J(w_0​,w_1, ... ,w_n)=\frac{1}{2m} \sum_{i=1}^{m}​(h(x^{(i)})−y^{(i)})^2  $$
<!-- $$ J(w_0​,w_1, ... ,w_n)=\frac{\sum_{i=1}^{m}​(h(x^{(i)})−y^{(i)})^2}{2m}   $$ -->

In [ ]:
def compute_cost(theta, X, y):
    m = len(y)
    h = hypothesis(X, theta)
    J = np.sum((h - y) ** 2) / (2 * m)
    return J

реалізуйте один крок градієнтного спуску;

$$  
\nabla J(\vec{w}) =
\begin{pmatrix}
\frac{\partial J(\vec{w})}{\partial w_0} \\
\frac{\partial J(\vec{w})}{\partial w_1} \\
\frac{\partial J(\vec{w})}{\partial w_2} \\
.. \\
\frac{\partial J(\vec{w})}{\partial w_n} \\
\end{pmatrix}
=
\begin{pmatrix}
\frac{1}{m} \sum_{i=1}^{m} (h(x^{(i)}) - y^{(i)})\\
\frac{1}{m} \sum_{i=1}^{m} (h(x^{(i)}) - y^{(i)})x_1^{(i)} \\
\frac{1}{m} \sum_{i=1}^{m} (h(x^{(i)}) - y^{(i)})x_2^{(i)} \\
.. \\
\frac{1}{m} \sum_{i=1}^{m} (h(x^{(i)}) - y^{(i)})x_n^{(i)} \\
\end{pmatrix}
$$

$$
X_{m,n}=
\begin{bmatrix}
 1&  x^{(1)}_{1}&  x^{(1)}_{2}&  …&  x^{(1)}_{n}  \\
 1&  x^{(2)}_{1}&  x^{(2)}_{2}&  …&  x^{(2)}_{n}  \\
 1&  x^{(3)}_{1}&  x^{(3)}_{2}&  …&  x^{(3)}_{n}  \\
 \vdots&   \vdots&   \vdots&   \ddots&  \vdots&   \\
 1&  x^{(m)}_{1}&  x^{(m)}_{2}&  …&  x^{(m)}_{n}  \\
\end{bmatrix}​​
$$

$$
∇J(\vec{w})=\frac{1}{m}​  X^T(X \vec{w} - \vec{y}​)
$$

In [ ]:
def gradient_descent_step(theta, X, y, alpha):
    m = len(y)
    h = hypothesis(X, theta)
    gradient = np.dot(X.T, (h - y)) / m
    new_theta = theta - alpha * gradient
    return new_theta

знайдіть найкращі параметри
𝑤
⃗
w
  для датасету використовуючи написані вами функції, прогнозуючу ціну на будинок залежно від площі, кількості ванних кімнат та кількості спалень;

In [ ]:
X=table_model[['area','bedrooms','bathrooms']].values
y=table_model['price'].values


In [ ]:
X_norm = feature_normalize(X[:, 1:])

X_norm = np.column_stack((np.ones(len(X_norm)), X_norm))
X_norm

array([[ 1.        ,  1.40341936,  1.42181174],
       [ 1.        ,  1.40341936,  5.40580863],
       [ 1.        ,  0.04727831,  1.42181174],
       ...,
       [ 1.        , -1.30886273, -0.57018671],
       [ 1.        ,  0.04727831, -0.57018671],
       [ 1.        ,  0.04727831, -0.57018671]])

In [ ]:
initial_w = np.random.rand(X.shape[1])

alpha = 0.001
iterations = 1000000
cost_history=[]
initial_w

array([0.2367207, 0.6863602, 0.6455067])

In [ ]:
for i in range(iterations):
    initial_w = gradient_descent_step(initial_w, X_norm, y, alpha)
    cost = compute_cost(initial_w, X_norm, y)
    cost_history.append(cost)

In [ ]:
print(initial_w)

[4766729.24770596  375771.3651489   826636.51519073]


# Аналітичне рішення

In [ ]:
def func(x,y):
  w = np.linalg.inv(X_norm.T.dot(X_norm)).dot(X_norm.T).dot(y)
  return w

In [ ]:
optimal_w=func(X_norm,y)
optimal_w

array([4766729.24770643,  375771.36514883,  826636.51519082])

# Використання  LinearRegression

In [ ]:
model=LinearRegression().fit(X_norm,y)
model.__dict__

{'fit_intercept': True,
 'copy_X': True,
 'n_jobs': None,
 'positive': False,
 'n_features_in_': 3,
 'coef_': array([     0.        , 375771.36514884, 826636.51519081]),
 'rank_': 2,
 'singular_': array([27.36406363, 18.47181695,  0.        ]),
 'intercept_': 4766729.247706422}

In [ ]:
sklearnw = np.append(model.intercept_, model.coef_[1:])
sklearnw

array([4766729.24770642,  375771.36514884,  826636.51519081])

# Порівняти результати

In [ ]:
print("Initial\t\t" ,initial_w)
print("SkLearn\t\t",sklearnw)
print("Analitic\t",optimal_w)

Initial		 [4766729.24770596  375771.3651489   826636.51519073]
SkLearn		 [4766729.24770642  375771.36514884  826636.51519081]
Analitic	 [4766729.24770643  375771.36514883  826636.51519082]


In [ ]:
price=data['price']
features=data[['area','bedrooms','bathrooms']]
X_train,X_test,y_train,y_test=train_test_split(features,price,test_size=0.2,random_state=10)


In [ ]:
regr=LinearRegression()
regr.fit(X_train,y_train)

print("Train data r-squared ",regr.score(X_train,y_train))
print("Test data r-squarded ",regr.score(X_test,y_test))

regr.__dict__
pd.DataFrame(data=regr.coef_,index=X_train.columns,columns=['coef'])

Train data r-squared  0.4788730700542939
Test data r-squarded  0.5092432268924044


coef
area       4.091322e+02
bedrooms   4.550391e+05
bathrooms  1.376909e+06